import type { Tool } from "./types"

export const tools: Tool[] = [
  // Text Generation
  {
    id: "chatgpt",
    name: "ChatGPT",
    shortDescription: "Conversational AI assistant",
    description:
      "ChatGPT is an AI-powered chatbot developed by OpenAI that can engage in natural conversations and assist with various tasks including writing, answering questions, and creative content generation.",
    categories: ["Text Generation", "Productivity"],
    url: "https://chat.openai.com",
    free: true,
    popular: true,
  },
  {
    id: "claude",
    name: "Claude",
    shortDescription: "AI assistant by Anthropic",
    description:
      "Claude is an AI assistant created by Vercel that can help with analysis, writing, math, coding, and creative tasks.",
    categories: ["Text Generation", "Productivity"],
    url: "https://claude.ai",
    free: true,
    popular: true,
  },
  {
    id: "gemini",
    name: "Google Gemini",
    shortDescription: "Google's AI chatbot",
    description:
      "Google Gemini is a conversational AI service that can help with various tasks including writing, analysis, and creative projects.",
    categories: ["Text Generation", "Productivity"],
    url: "https://gemini.google.com",
    free: true,
    popular: true,
  },
  {
    id: "perplexity",
    name: "Perplexity AI",
    shortDescription: "AI-powered search engine",
    description: "Perplexity AI combines search and AI to provide accurate, cited answers to questions.",
    categories: ["Text Generation", "Productivity"],
    url: "https://www.perplexity.ai",
    free: true,
  },
  {
    id: "jasper",
    name: "Jasper",
    shortDescription: "AI content creation platform",
    description:
      "Jasper is an AI content creation platform that helps teams create marketing copy, social media posts, and other content with AI assistance.",
    categories: ["Text Generation", "Productivity"],
    url: "https://www.jasper.ai",
    free: false,
  },
  {
    id: "copy-ai",
    name: "Copy.ai",
    shortDescription: "AI copywriting tool",
    description: "Copy.ai helps create marketing copy, blog posts, and other written content using AI.",
    categories: ["Text Generation", "Productivity"],
    url: "https://www.copy.ai",
    free: true,
  },
  {
    id: "writesonic",
    name: "Writesonic",
    shortDescription: "AI writing assistant",
    description: "Writesonic is an AI writing tool that helps create articles, ads, emails, and website copy.",
    categories: ["Text Generation", "Productivity"],
    url: "https://writesonic.com",
    free: true,
  },
  {
    id: "grammarly",
    name: "Grammarly",
    shortDescription: "AI writing assistant",
    description: "Grammarly uses AI to help improve writing by checking grammar, spelling, and style.",
    categories: ["Text Generation", "Productivity"],
    url: "https://www.grammarly.com",
    free: true,
  },
  {
    id: "notion-ai",
    name: "Notion AI",
    shortDescription: "AI-powered workspace",
    description:
      "Notion AI integrates artificial intelligence into the Notion workspace for writing, brainstorming, and organizing.",
    categories: ["Text Generation", "Productivity"],
    url: "https://www.notion.so/product/ai",
    free: false,
  },
  {
    id: "quillbot",
    name: "QuillBot",
    shortDescription: "AI paraphrasing tool",
    description: "QuillBot uses AI to paraphrase, summarize, and improve writing quality.",
    categories: ["Text Generation", "Productivity"],
    url: "https://quillbot.com",
    free: true,
  },
  {
    id: "rytr",
    name: "Rytr",
    shortDescription: "AI writing assistant",
    description: "Rytr is an AI writing assistant that helps create content for blogs, ads, emails, and more.",
    categories: ["Text Generation", "Productivity"],
    url: "https://rytr.me",
    free: true,
  },
  {
    id: "wordtune",
    name: "Wordtune",
    shortDescription: "AI writing companion",
    description: "Wordtune helps rewrite and improve text to make it clearer and more engaging.",
    categories: ["Text Generation", "Productivity"],
    url: "https://www.wordtune.com",
    free: true,
  },

  // Image Generation
  {
    id: "midjourney",
    name: "Midjourney",
    shortDescription: "AI image generation",
    description:
      "Midjourney is an AI art generator that creates images from textual descriptions, allowing users to create stunning visuals without traditional design skills.",
    categories: ["Image Generation"],
    url: "https://www.midjourney.com",
    free: false,
    popular: true,
  },
  {
    id: "dall-e",
    name: "DALL-E",
    shortDescription: "AI image creation from text",
    description:
      "DALL-E is an AI system by OpenAI that can create realistic images and art from natural language descriptions, enabling creative visual content generation.",
    categories: ["Image Generation"],
    url: "https://openai.com/dall-e-3",
    free: false,
    popular: true,
  },
  {
    id: "stable-diffusion",
    name: "Stable Diffusion",
    shortDescription: "Open-source image generation",
    description: "Stable Diffusion is an open-source AI model for generating images from text descriptions.",
    categories: ["Image Generation"],
    url: "https://stability.ai/stable-diffusion",
    free: true,
    popular: true,
  },
  {
    id: "leonardo-ai",
    name: "Leonardo.ai",
    shortDescription: "AI art generation platform",
    description: "Leonardo.ai is a creative AI platform for generating production-quality visual assets.",
    categories: ["Image Generation"],
    url: "https://leonardo.ai",
    free: true,
  },
  {
    id: "canva-ai",
    name: "Canva AI",
    shortDescription: "AI-powered design tool",
    description: "Canva's AI features help create designs, generate images, and enhance photos.",
    categories: ["Image Generation", "Productivity"],
    url: "https://www.canva.com/ai-image-generator/",
    free: true,
  },
  {
    id: "adobe-firefly",
    name: "Adobe Firefly",
    shortDescription: "Creative AI by Adobe",
    description: "Adobe Firefly is a family of creative generative AI models for generating images and text effects.",
    categories: ["Image Generation"],
    url: "https://www.adobe.com/products/firefly.html",
    free: true,
  },
  {
    id: "artbreeder",
    name: "Artbreeder",
    shortDescription: "Collaborative AI art tool",
    description: "Artbreeder allows users to create and modify images using AI and collaborative breeding.",
    categories: ["Image Generation"],
    url: "https://www.artbreeder.com",
    free: true,
  },
  {
    id: "remove-bg",
    name: "Remove.bg",
    shortDescription: "AI background removal",
    description: "Remove.bg uses AI to automatically remove backgrounds from images.",
    categories: ["Image Generation"],
    url: "https://www.remove.bg",
    free: true,
  },
  {
    id: "ideogram",
    name: "Ideogram",
    shortDescription: "AI image generator with text",
    description: "Ideogram specializes in generating images with readable text and typography.",
    categories: ["Image Generation"],
    url: "https://ideogram.ai",
    free: true,
  },
  {
    id: "flux",
    name: "Flux",
    shortDescription: "Advanced AI image generation",
    description: "Flux is a state-of-the-art AI image generation model with high-quality outputs.",
    categories: ["Image Generation"],
    url: "https://flux1.ai",
    free: true,
  },
  {
    id: "playground-ai",
    name: "Playground AI",
    shortDescription: "AI art creation platform",
    description: "Playground AI offers various AI models for creating and editing images.",
    categories: ["Image Generation"],
    url: "https://playgroundai.com",
    free: true,
  },
  {
    id: "nightcafe",
    name: "NightCafe",
    shortDescription: "AI art generator",
    description: "NightCafe creates AI-generated artwork using various algorithms and styles.",
    categories: ["Image Generation"],
    url: "https://nightcafe.studio",
    free: true,
  },

  // Audio
  {
    id: "eleven-labs",
    name: "ElevenLabs",
    shortDescription: "AI voice generation",
    description:
      "ElevenLabs provides AI voice technology that can generate realistic speech in various languages and voices, useful for content creators and developers.",
    categories: ["Audio"],
    url: "https://elevenlabs.io",
    free: true,
    popular: true,
  },
  {
    id: "murf",
    name: "Murf",
    shortDescription: "AI voice generator",
    description:
      "Murf is an AI voice generator that creates realistic voiceovers for videos, presentations, and other content.",
    categories: ["Audio"],
    url: "https://murf.ai",
    free: true,
  },
  {
    id: "speechify",
    name: "Speechify",
    shortDescription: "Text-to-speech AI",
    description: "Speechify converts text to natural-sounding speech using AI voices.",
    categories: ["Audio"],
    url: "https://speechify.com",
    free: true,
  },
  {
    id: "descript",
    name: "Descript",
    shortDescription: "All-in-one audio/video editor",
    description:
      "Descript is an all-in-one audio and video editing tool that uses AI to transcribe and edit content as easily as editing a text document.",
    categories: ["Audio", "Video"],
    url: "https://www.descript.com",
    free: true,
  },
  {
    id: "otter-ai",
    name: "Otter.ai",
    shortDescription: "AI meeting transcription",
    description: "Otter.ai provides real-time transcription and meeting notes using AI.",
    categories: ["Audio", "Productivity"],
    url: "https://otter.ai",
    free: true,
  },
  {
    id: "suno",
    name: "Suno",
    shortDescription: "AI music generation",
    description: "Suno creates original music and songs from text prompts using AI.",
    categories: ["Audio"],
    url: "https://suno.com",
    free: true,
    popular: true,
  },
  {
    id: "boomy",
    name: "Boomy",
    shortDescription: "AI music creation",
    description: "Boomy allows users to create original music tracks using AI in seconds.",
    categories: ["Audio"],
    url: "https://boomy.com",
    free: true,
  },
  {
    id: "udio",
    name: "Udio",
    shortDescription: "AI music generator",
    description: "Udio creates high-quality music tracks from text descriptions using AI.",
    categories: ["Audio"],
    url: "https://www.udio.com",
    free: true,
  },
  {
    id: "resemble-ai",
    name: "Resemble AI",
    shortDescription: "AI voice cloning",
    description: "Resemble AI creates custom AI voices and voice cloning technology.",
    categories: ["Audio"],
    url: "https://www.resemble.ai",
    free: false,
  },
  {
    id: "whisper",
    name: "OpenAI Whisper",
    shortDescription: "AI speech recognition",
    description: "Whisper is an automatic speech recognition system that converts audio to text.",
    categories: ["Audio"],
    url: "https://openai.com/research/whisper",
    free: true,
  },

  // Video
  {
    id: "runway",
    name: "Runway",
    shortDescription: "AI video editing and generation",
    description:
      "Runway is a creative toolkit powered by AI that allows users to edit and generate videos with advanced AI features like text-to-video generation.",
    categories: ["Video", "Image Generation"],
    url: "https://runwayml.com",
    free: false,
    popular: true,
  },
  {
    id: "pika-labs",
    name: "Pika Labs",
    shortDescription: "AI video generation",
    description: "Pika Labs creates videos from text prompts and images using AI.",
    categories: ["Video"],
    url: "https://pika.art",
    free: true,
  },
  {
    id: "synthesia",
    name: "Synthesia",
    shortDescription: "AI video creation platform",
    description: "Synthesia creates AI-generated videos with virtual presenters from text scripts.",
    categories: ["Video"],
    url: "https://www.synthesia.io",
    free: false,
  },
  {
    id: "loom-ai",
    name: "Loom AI",
    shortDescription: "AI-powered screen recording",
    description: "Loom uses AI to enhance screen recordings with automatic titles, summaries, and chapters.",
    categories: ["Video", "Productivity"],
    url: "https://www.loom.com",
    free: true,
  },
  {
    id: "pictory",
    name: "Pictory",
    shortDescription: "AI video creation from text",
    description: "Pictory creates short videos from long-form content using AI.",
    categories: ["Video"],
    url: "https://pictory.ai",
    free: true,
  },
  {
    id: "invideo-ai",
    name: "InVideo AI",
    shortDescription: "AI video generator",
    description: "InVideo AI creates videos from text prompts with automated editing and voiceovers.",
    categories: ["Video"],
    url: "https://invideo.io/ai/",
    free: true,
  },
  {
    id: "heygen",
    name: "HeyGen",
    shortDescription: "AI avatar video generator",
    description: "HeyGen creates videos with AI avatars that can speak in multiple languages.",
    categories: ["Video"],
    url: "https://www.heygen.com",
    free: true,
  },
  {
    id: "fliki",
    name: "Fliki",
    shortDescription: "Text to video AI",
    description: "Fliki converts text into videos with AI voices and visuals.",
    categories: ["Video"],
    url: "https://fliki.ai",
    free: true,
  },
  {
    id: "luma-ai",
    name: "Luma AI",
    shortDescription: "3D capture and AI video",
    description: "Luma AI creates 3D content and AI-generated videos from various inputs.",
    categories: ["Video"],
    url: "https://lumalabs.ai",
    free: true,
  },

  // Data Analysis
  {
    id: "huggingface",
    name: "Hugging Face",
    shortDescription: "AI model hub and tools",
    description:
      "Hugging Face is a platform that provides tools for building, training and deploying state-of-the-art machine learning models with a focus on natural language processing.",
    categories: ["Text Generation", "Image Generation", "Data Analysis"],
    url: "https://huggingface.co",
    free: true,
    popular: true,
  },
  {
    id: "tableau-ai",
    name: "Tableau AI",
    shortDescription: "AI-powered data visualization",
    description: "Tableau uses AI to help create data visualizations and insights automatically.",
    categories: ["Data Analysis"],
    url: "https://www.tableau.com/products/tableau-ai",
    free: false,
  },
  {
    id: "julius-ai",
    name: "Julius AI",
    shortDescription: "AI data analyst",
    description: "Julius AI helps analyze data and create visualizations through natural language conversations.",
    categories: ["Data Analysis"],
    url: "https://julius.ai",
    free: true,
  },
  {
    id: "pandas-ai",
    name: "PandasAI",
    shortDescription: "AI for data analysis",
    description: "PandasAI adds AI capabilities to pandas for natural language data analysis.",
    categories: ["Data Analysis"],
    url: "https://pandas-ai.readthedocs.io",
    free: true,
  },
  {
    id: "akkio",
    name: "Akkio",
    shortDescription: "No-code AI platform",
    description: "Akkio enables users to build and deploy machine learning models without coding.",
    categories: ["Data Analysis"],
    url: "https://www.akkio.com",
    free: true,
  },
  {
    id: "dataiku",
    name: "Dataiku",
    shortDescription: "AI and ML platform",
    description: "Dataiku provides a collaborative platform for data science and machine learning.",
    categories: ["Data Analysis"],
    url: "https://www.dataiku.com",
    free: false,
  },
  {
    id: "h2o-ai",
    name: "H2O.ai",
    shortDescription: "Open source AI platform",
    description: "H2O.ai provides open source machine learning and AI platforms for enterprises.",
    categories: ["Data Analysis"],
    url: "https://h2o.ai",
    free: true,
  },

  // Code Generation
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    shortDescription: "AI pair programmer",
    description:
      "GitHub Copilot is an AI-powered code completion tool that helps developers write code faster by suggesting whole lines or blocks of code as they type.",
    categories: ["Code Generation", "Productivity"],
    url: "https://github.com/features/copilot",
    free: false,
    popular: true,
  },
  {
    id: "cursor",
    name: "Cursor",
    shortDescription: "AI code editor",
    description: "Cursor is an AI-powered code editor built for pair programming with AI.",
    categories: ["Code Generation", "Productivity"],
    url: "https://cursor.sh",
    free: true,
    popular: true,
  },
  {
    id: "replit-ai",
    name: "Replit AI",
    shortDescription: "AI coding assistant",
    description: "Replit AI helps with coding, debugging, and explaining code in the Replit environment.",
    categories: ["Code Generation", "Productivity"],
    url: "https://replit.com/ai",
    free: true,
  },
  {
    id: "v0-vercel",
    name: "v0 by Vercel",
    shortDescription: "AI UI generator",
    description: "v0 by Vercel generates React components and full applications from text prompts using AI.",
    categories: ["Code Generation"],
    url: "https://v0.dev",
    free: true,
    popular: true,
  },
  {
    id: "claude-artifacts",
    name: "Claude Artifacts",
    shortDescription: "AI code and app generator",
    description: "Claude can generate interactive code, applications, and documents through its Artifacts feature.",
    categories: ["Code Generation", "Text Generation"],
    url: "https://claude.ai",
    free: true,
  },
  {
    id: "bolt-new",
    name: "Bolt.new",
    shortDescription: "AI full-stack development",
    description: "Bolt.new creates full-stack applications from prompts with live preview and deployment.",
    categories: ["Code Generation"],
    url: "https://bolt.new",
    free: true,
  },
  {
    id: "lovable",
    name: "Lovable",
    shortDescription: "AI app builder",
    description: "Lovable builds full-stack applications from natural language descriptions using AI.",
    categories: ["Code Generation"],
    url: "https://lovable.dev",
    free: true,
  },
  {
    id: "codeium",
    name: "Codeium",
    shortDescription: "AI coding assistant",
    description: "Codeium provides AI-powered code completion, chat, and search across multiple IDEs.",
    categories: ["Code Generation", "Productivity"],
    url: "https://codeium.com",
    free: true,
  },
  {
    id: "tabnine",
    name: "Tabnine",
    shortDescription: "AI code completion",
    description: "Tabnine provides AI-powered code completion and suggestions for developers.",
    categories: ["Code Generation", "Productivity"],
    url: "https://www.tabnine.com",
    free: true,
  },
  {
    id: "amazon-codewhisperer",
    name: "Amazon CodeWhisperer",
    shortDescription: "AI coding companion",
    description: "Amazon CodeWhisperer generates code suggestions and helps with coding tasks using AI.",
    categories: ["Code Generation", "Productivity"],
    url: "https://aws.amazon.com/codewhisperer/",
    free: true,
  },
  {
    id: "sourcegraph-cody",
    name: "Sourcegraph Cody",
    shortDescription: "AI coding assistant",
    description: "Cody is an AI coding assistant that helps write, understand, and fix code.",
    categories: ["Code Generation", "Productivity"],
    url: "https://sourcegraph.com/cody",
    free: true,
  },
  {
    id: "continue-dev",
    name: "Continue",
    shortDescription: "Open-source AI code assistant",
    description: "Continue is an open-source AI code assistant that integrates with VS Code and JetBrains IDEs.",
    categories: ["Code Generation", "Productivity"],
    url: "https://continue.dev",
    free: true,
  },
  {
    id: "aider",
    name: "Aider",
    shortDescription: "AI pair programming in terminal",
    description: "Aider is a command-line AI coding assistant that helps edit code in your terminal.",
    categories: ["Code Generation", "Productivity"],
    url: "https://aider.chat",
    free: true,
  },
  {
    id: "windsurf",
    name: "Windsurf",
    shortDescription: "AI-powered IDE",
    description: "Windsurf is an AI-native IDE that combines coding with AI assistance seamlessly.",
    categories: ["Code Generation", "Productivity"],
    url: "https://codeium.com/windsurf",
    free: true,
  },
  {
    id: "devin-ai",
    name: "Devin AI",
    shortDescription: "AI software engineer",
    description: "Devin is an AI software engineer that can plan, code, and deploy applications autonomously.",
    categories: ["Code Generation"],
    url: "https://www.cognition-labs.com/introducing-devin",
    free: false,
  },

  // Productivity
  {
    id: "zapier-ai",
    name: "Zapier AI",
    shortDescription: "AI workflow automation",
    description: "Zapier uses AI to help create and optimize automated workflows between apps.",
    categories: ["Productivity"],
    url: "https://zapier.com/ai",
    free: true,
  },
  {
    id: "reclaim-ai",
    name: "Reclaim.ai",
    shortDescription: "AI calendar scheduling",
    description: "Reclaim.ai uses AI to automatically schedule and protect time for important tasks.",
    categories: ["Productivity"],
    url: "https://reclaim.ai",
    free: true,
  },
  {
    id: "superhuman",
    name: "Superhuman",
    shortDescription: "AI email client",
    description: "Superhuman uses AI to help manage email more efficiently with smart features and shortcuts.",
    categories: ["Productivity"],
    url: "https://superhuman.com",
    free: false,
  },
  {
    id: "mem-ai",
    name: "Mem",
    shortDescription: "AI note-taking",
    description: "Mem is an AI-powered note-taking app that helps organize and surface relevant information.",
    categories: ["Productivity"],
    url: "https://mem.ai",
    free: true,
  },
  {
    id: "lex",
    name: "Lex",
    shortDescription: "AI writing tool",
    description: "Lex is an AI-powered writing tool designed for long-form content creation.",
    categories: ["Productivity", "Text Generation"],
    url: "https://lex.page",
    free: true,
  },
  {
    id: "calendly-ai",
    name: "Calendly AI",
    shortDescription: "AI scheduling assistant",
    description: "Calendly uses AI to optimize meeting scheduling and reduce back-and-forth communication.",
    categories: ["Productivity"],
    url: "https://calendly.com",
    free: true,
  },
  {
    id: "clickup-ai",
    name: "ClickUp AI",
    shortDescription: "AI project management",
    description: "ClickUp AI helps with project management, task creation, and workflow optimization.",
    categories: ["Productivity"],
    url: "https://clickup.com/ai",
    free: true,
  },
  {
    id: "monday-ai",
    name: "Monday.com AI",
    shortDescription: "AI work management",
    description: "Monday.com uses AI to enhance work management and team collaboration.",
    categories: ["Productivity"],
    url: "https://monday.com/ai",
    free: false,
  },
  {
    id: "tome",
    name: "Tome",
    shortDescription: "AI presentation maker",
    description: "Tome creates presentations and documents using AI from simple prompts.",
    categories: ["Productivity"],
    url: "https://tome.app",
    free: true,
  },
  {
    id: "gamma",
    name: "Gamma",
    shortDescription: "AI presentation generator",
    description: "Gamma creates beautiful presentations, documents, and websites using AI.",
    categories: ["Productivity"],
    url: "https://gamma.app",
    free: true,
  },
]
